name: educonnect_app
description: EduConnect MVP demo app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  socket_io_client: ^2.0.0
  url_launcher: ^6.3.0
  image_picker: ^0.8.7+4
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
